### ISSUE TITLE
improvements to autosend feature

### ISSUE THREAD

**Issue by dl1jbe** [Tlf/tlf#12]
The recent work on autosend needs some further improvements:

from Martin OK1RR:
- an indicator of the ON state of Autosend. I suggest different color
 in the call field till the "length" set, ie. if :char set to 4, the
 first 4 characters in the call field should have different background
 color. If the color change is a problem, there should be a vertical
 bar instead, an asterisk or arrow etc.
 
- the question mark in a special meaning. If an ? is typed, the
 autosend should immediately send out the contents of the call field
 BUT the cursor should never move to the exchange field. Optimal would
 be an immediate action, not dependent on the length of the string
 already typed.

- The Autosend feature has mostly an autoswitch-off
 when first slash / appears. Calls like HB0/DL1JBE/P can be hardly
 completed within considered time span. Very useful would be also a
 "panic" autosend-off switch (a single key, easily accessible like ,
 or .). Very useful for calls like WA4DHN/VP2M or OK1JFQ/P...

**Comment by dh5fs** [comment]
Maybe we should still enable the possiblity to start autosend manually. This could be helpful for some. Eg. option "m" enables SPACE/DOWN-ARROW to start transmitting, at any time. Entering letters is still possible. When TX has finshed the cursor jumps to the exchange field as ususal.

[QUOTE from man]
:CHAr Input number of characters for CW auto-start. Default is 0 (off).
       You can also start sending the  first  part  of  the  call  by  hitting
       ’space’ of ’down-arrow’.  This works only in CW CONTEST modes.

**Comment by dl1jbe** [comment]
Sorry, I do not undertand. What do you mean by 'option "m"' please. Where should that option be used or set. 

And btw, the quotet man page is from a version 'before' we changed the autosend feature.
If I get you right, you wanted to have the automatic version and the manual start as well?

**Comment by dh5fs** [comment]
Yes, thats the manual trigger to start send to we abanoned with implementing the autosend feature. But for less expirienced telegraphists it might be better to start sending manually. This could be enabled with option "m".

**Comment by dl1jbe** [comment]
Implemented with last commit. Activate with :char and 'm' for manual. Press Enter any time and tlf will start sending the call. The rest stays unchanged.
Please test and give feedback.

**Comment by dh5fs** [comment]
Works like a charm in manual mode!! CW daemon version 0.9.4.

**Comment by dl1jbe** [comment]
Glad to hear. So I am closing the issue. Please reopen if needed.
