### ISSUE TITLE
QSO counts per band are not shown when opening a non-empty log

### ISSUE THREAD

**Issue by zcsahok** [Tlf/tlf#138]
Log is loaded but QSO counts are 0.

![image](https://user-images.githubusercontent.com/15141948/68335035-08e12780-00dc-11ea-8df8-dd741f04427f.png)

Should be (and was) like this:

![image](https://user-images.githubusercontent.com/15141948/68335205-52317700-00dc-11ea-99a4-80d122d94e90.png)

Caused by a change in 766e0f4.
The root cause is that functions are not (only) doing what their name says.
Original code (main.c):

```
scroll_log();
nr_qsos = readcalls();
```
Looks not too logical: why to call `scroll_log` before actually loading the log?

Updated code:
```
nr_qsos = readcalls();
scroll_log();
```

But at the end of `readcalls` the counts (and other stuff) are reset if `qsonum==1`.
And `qsonum` is set not in `readcalls` as one would expect, but in `scroll_log`...
So if they are called in "wrong" order the QSO counts are lost. (and maybe other info also, who knows)

**Comment by dl1jbe** [comment]
Confirmed. Will be fixed soon. 

The check at end of readcalls is a leftover from long ago, but it seems it has to be dropped now.

**Comment by dl1jbe** [comment]
Both problems are fixed. Please test and close the issue if no more problems left

**Comment by zcsahok** [comment]
Both are fixed, closing the issue. Thanks.
