### ISSUE TITLE
Return from terminal editor results in arrow keys not working

### ISSUE THREAD

**Issue by N0NB** [Tlf/tlf#144]
I noticed when testing some fixes for CT mode that using a terminal mode editor results in the arrow keys only putting their letter representations--A, B, C, or D--into an entry field.

To reproduce, use the :SET, :CFG, or :EDIT command with a terminal editor defined in logcfg.dat.  When the editor is exited and Tlf resumes control of the screen, try using the keyboard arrow keys.

I have confirmed this with vim, nano, and mcedit.  My one try with gedit, a GUI editor, that did not take control of the terminal screen resulted in normal arrow key behavior when gedit was exited and control was resumed by Tlf.

I suspect we're not resetting or configuring the terminal completely/correctly after the terminal editor exits.

**Comment by dl1jbe** [comment]
Hi,

Thanks for the report.
I can confirm it here. Let me look into it.


Am Mon, 02 Dec 2019 10:53:21 -0800
schrieb Nate Bargmann <notifications@github.com>:

> I noticed when testing some fixes for CT mode that using a terminal
> mode editor results in the arrow keys only putting their letter
> representations--A, B, C, or D--into an entry field.
> 
> To reproduce, use the :SET, :CFG, or :EDIT command with a terminal
> editor defined in logcfg.dat.  When the editor is exited and Tlf
> resumes control of the screen, try using the keyboard arrow keys.
> 
> I have confirmed this with vim, nano, and mcedit.  My one try with
> gedit, a GUI editor, that did not take control of the terminal screen
> resulted in normal arrow key behavior when gedit was exited and
> control was resumed by Tlf.
> 
> I suspect we're not resetting or configuring the terminal
> completely/correctly after the terminal editor exits.
> 
> 



-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by zcsahok** [comment]
`logview` (less) works. It seems adding `endwin()` before and `clear_display+refreshp` after `system` helps.

**Comment by N0NB** [comment]
You're correct, Zoli, the log view does work here as well.  I failed to note that originally.

**Comment by zcsahok** [comment]
This worked for me:
```
    endwin();        //<<<

    cmdstr = g_strdup_printf("%s %s", editor, filename);
    retval = (system(cmdstr));;
    if (WEXITSTATUS(retval) == 127) {
	TLF_LOG_WARN("Can not start editor, check EDITOR= command");
    }
    g_free(cmdstr);

    clear_display(); //<<<
    refreshp();      //<<<
```

**Comment by dl1jbe** [comment]
Right. with some corrections.

> This worked for me:
> 
> ```
>     endwin();        //<<< That one is needed
> 
>     cmdstr = g_strdup_printf("%s %s", editor, filename);
>     retval = (system(cmdstr));;

>     refreshp();      //<<< Has to be here so that we can display the TLF_WARN 

>     if (WEXITSTATUS(retval) == 127) {
> 	TLF_LOG_WARN("Can not start editor, check EDITOR= command");
>     }
>     g_free(cmdstr);
> 
>     clear_display(); //<<< That one can be left out
> ```

**Comment by dl1jbe** [comment]
Fixed version in repository. Please test and close issue if fixed.

**Comment by N0NB** [comment]
I'll test this, Tom.  BTW, I have the warnings generated by parse_logcfg.c fixed in a branch I'll be pushing out and issuing a pull request from in a day or two.

**Comment by N0NB** [comment]
My quick test shows this is fixed.  Thanks, guys!
