### ISSUE TITLE
ALT-T for tune does not work anymore

### ISSUE THREAD

**Issue by dh5fs** [Tlf/tlf#163]
tested with latest build from master, 20200315
laste working version here 1.3.0
cwdaemon version 0.10.2

**Comment by dl1jbe** [comment]
Works here with tlf-1.32., tlf-1.4 and master branch with cwdaemon and winkeydaemon

Try to start cwdaemon with the following parameters:
'-n' (stay in foreground) and '-y d' (enable debug output).
Please check if it receives commands from tlf and report back.

**Comment by zcsahok** [comment]
No issue with cwdaemon 0.10.2-2 and tlf built from master on 19.3.

**Comment by airween** [comment]
```
$ cwdaemon -V
cwdaemon version 0.10.1
$ tlf -V
tlf-1.5~git
$ git rev-parse HEAD
00b5d6ba157d55763cb98bca23b1592992016c07
```
(This is the current master on 20th of March.)

Works as well.

**Comment by dl1jbe** [comment]
@dh5fs Any news Fred?

**Comment by dl1jbe** [comment]
Closing it, as we can not confirm it and further information are missing.
Please reopen if needed.
