### ISSUE TITLE
No direct frequency entry for 60m

### ISSUE THREAD

**Issue by zcsahok** [Tlf/tlf#173]
Entering `5310` on call input field doesn't change to 60m. Non-contest mode is set and direct frequency entry works for other WARC bands like `10110` or `24910`.

@dl8dtl any idea?

**Comment by zcsahok** [comment]
Solved, it was an issue with my rig. Had to set it to general (`GENE`) mode to be able to tune out of the classic+WARC ham bands.
Closing the issue.

**Comment by dl8dtl** [comment]
Glad you found it.

73!
