### ISSUE TITLE
Keyword 'CABRILLO-MODE' not supported error for default cqww contest

### ISSUE THREAD

**Issue by wvolz** [Tlf/tlf#262]
After a pull and recompile I've started to get the following error when using the default logcfg:

Keyword 'CABRILLO-MODE' not supported error for default cqww contest

If I remove that from the cqww rules file TLF starts up ok. Version from "git describe" is "tlf-1.4.1-165-g080f551".

**Comment by zcsahok** [comment]
Thanks for spotting!

It's a typo, the keyword is actually `CABRILLO-CATEGORY-MODE`.

**Comment by wvolz** [comment]
Thanks!
