### ISSUE TITLE
Info line going missing

### ISSUE THREAD

**Issue by dh5fs** [Tlf/tlf#266]
version: test with newest master build, in WPX
whats wrong: in ESM mode after entering the call, the lowest line with (distance heading etc.) disappears, this can be annoying when you need to turn the beam because Sig went down. Does not happen when changing with space to the number field.
how it should be: line just stays until number was entered

**Comment by dl1jbe** [comment]
That behavior is already seen at least since tlf-1.4.1. But you are right, it would be better to keep that information visible  as long as possible. 
I will look into it.

**Comment by dl1jbe** [comment]
As #279 is merged in let us close the issue now.
