### ISSUE TITLE
regressions with the actual master

### ISSUE THREAD

**Issue by dh5fs** [Tlf/tlf#280]
1. when using SHIFT-F1 if you want to return to your CQ frequency (in MEM) after S&P some Calls are filled in, expectation would be to have a clear call input field
2. when changing CW speed and a call is in the input field, some letters are added there, expection: no letters anywhere when using <PG-UP, PG-DWN> for changing CW speed

**Comment by dh5fs** [comment]
3. one more: there seems to be a new directory structures since some time. I always install with the --prefix option, after that actual TLF does not find the eg. rules directory, which needs to be now under /bin/rules, but was before under /share/tlf/rules. Same is true for logcfg.dat, cty.dat etc. they are not found. So basically install with --prefix does not work properly.
Actually the new structure is better, but does not get installed.

**Comment by dl1jbe** [comment]
PgUp/PgDwn problem got fixed in master branch

**Comment by dh5fs** [comment]
issues #1 and #2 seem to be fixed, thanks Tom.
