### ISSUE TITLE
Bad interaction between RECALL_MULTS and Ctrl-A add spot

### ISSUE THREAD

**Issue by df7cb** [Tlf/tlf#313]
When RECALL_MULTS is active, and I use Ctrl-A to add a spot for someone I have worked before (when I see them again on the band), then when the next QSO is logged, the old exchange from the spotted call is filled into the exchange field for the next QSO.

How to reproduce:
* enable RECALL_MULTS
* select a contest that uses serials and doesn't prefill exchanges
* log someone: N0CALL 123
* spot them: N0CALL Ctrl-A (with freq from rig, or manually entered when tlf asks)
* log someone else: N1CALL
* the exchange field gets "123" filled in

![2022-02-23 180714 c6Nffa](https://user-images.githubusercontent.com/1021828/155370110-ffedd582-8bbb-4d59-8e76-bd022476d616.png)

**Comment by airween** [comment]
I tried the steps above with MWC rules + `RECALL_MULTS`, but couldn't reproduce this issue.

In what mode are you? `Log` or `S&P`?

Btw: may be you can check the `BMAUTOADD` and `BMAUTOGRAB` keywords. `BMAUTOADD` does exactly the same as `CTRL+A`, without any manual interaction - if you are in `S&P` mode.

**Comment by df7cb** [comment]
I can reproduce it with this setup:
* start in an empty directory
* mkdir rules
* touch rules/contest
* logcfg.dat:
```
CONTEST=contest
CALL=DF7CB
RECALL_MULTS
```
In Tlf then type:
* n0call\<enter>123\<enter>
* n0call\<ctrl-a>14001\<enter>
* n1call<enter>
* "123" appears

Log/S&P shouldn't matter, I've seen it in both (reproduced in Log now)

Thanks for the BMAUTO* pointers, I should re-read the whole manpage now that I understand more about using dxclusters!

**Comment by airween** [comment]
Chirstoph, thanks for your help - but unfortunately I still can't reproduce the issue.

I followed exactly your steps, but the `123` has not appeared.

Now I updated Tlf to be sure that I'm using the most fresh version.

I'm on master branch, and the version:
```
$ git describe 
tlf-1.4.1-245-g2b5c837
```

I also made a [video](https://www.dropbox.com/s/rnhojx77q3m7wbx/tlf_recall_issue-2022-02-23_20.44.22.mp4).

Can anyone reproduce the problem?

**Comment by df7cb** [comment]
Same git commit here. I was building using the Debian packaging (symlinking debian/), but I can also reproduce it using autoreconf -i; ./configure; make and then invoking ../src/tlf from the temp dir. (Plus symlinking cty.dat.)

I have no idea yet what might be different.

**Comment by dl1jbe** [comment]
Had a chance to test your minimal setup here too, Christoph.
Works fine, without problems.

According to the code Ctrl-A does only record call sign, time and frequency. There is no obvious connection to the function doing the recall of old exchange data. 

Can you please check if the problem only exists when you use Ctrl-A? 
Second test: Does it only happens with N0CALL and N1CALL or with other calls also?

**Comment by zcsahok** [comment]
The issue can be reproduced event with latest master (`tlf-1.4.1-256-g6a4e0c1`) and without Ctrl-A.

1. build a fresh clone
2. set up the `tmp` dir as described by @df7cb 
3. run `../src/tlf -rn` (no radio, no cluster)
4. log N0CALL on 40m with exchange 123 (CQ mode)
5. optionally change to 20m to avoid getting dupe warning in next step
6. start logging N0CALL but only enter the call: `N0CALL`
7. clear call input field using backspace (not escape!): 6 x `<Backspace>`
8. enter any other call: `TE1ST`
9. press `<Enter>`
10. exchange field shows `123`

**Comment by df7cb** [comment]
Thanks Zoltan, I was out of ideas how to describe it further...

**Comment by dl1jbe** [comment]
Tried to reproduce the bug today. First try in the morning:
- Worked as expected in the beginning, but showed the problem afterwards consistently.
- That confirms that there is a bug.

Second try just now to l
- I am not able to reproduce the error again.  It just works. Damn.
