### ISSUE TITLE
Review usage of fgets in file reading

### ISSUE THREAD

**Issue by zcsahok** [Tlf/tlf#348]
Follow-up from #345:

As the problem with long lines pops up from time to time, maybe we should check all `fgets()` invocations for truncation of input due to limit buffer size.
There is another function `getline()` which seems better fit this use case.

**Comment by dl1jbe** [comment]
Scanning thru the code there are quite some places where 'fgets()' is used. 

For start it may be best to begin with user provided files (multipliers, config.dat, rules file, initial_exchange, maybe cabrillo.fmt).

**Comment by darvark** [comment]
I had some free time during my vacations and I've prepared code change that contains replacement of all fgets with getline function. Tests passes, tlf seems to work without problem. Soon I'll add pull-request

**Comment by zcsahok** [comment]
Fixed by #403
