### ISSUE TITLE
Make boolean configs symmetric

### ISSUE THREAD

**Issue by zcsahok** [Tlf/tlf#357]
Currently boolean config parameters can only be set to true.
Once a parameter is set in `logcfg.dat` there is no way to set it back in the rule file.

Config handling can be easily extended in a backward compatible way:
- PARAM : sets it to true; this is the current behavior
- PARAM=true (or yes) : also sets it to true (new)
- PARAM=false (or no) : sets it to false (new)
- PARAM=none of the above : error

This change would allow us to define configs that are true by default
thus avoiding the somewhat mentally hard to grab negative logic (NOxxx like NOAUTOCQ).
Maybe we can even change the recently added NO_LEADING_ZEROS_SERIAL to LEADING_ZEROS_SERIAL, if it is not too late.

I can provide a PR for this.

**Comment by dl1jbe** [comment]
Good idea. Please provide a PR. 
I had a similar feeling about the need for a setting to false for different settings. So it would be really nice to have.

**Comment by N0NB** [comment]
Super good idea, Zoli.
