### ISSUE TITLE
Feature request : CW keying via hamlib

### ISSUE THREAD

**Issue by sp7q** [Tlf/tlf#410]
CW keying via HamLib through "b" command line in this thread : 
https://www.cqrlog.com/node/1484

**Comment by zcsahok** [comment]
I believe this works already (see #294). Please check the `HAMLIB_KEYER` keyword.

**Comment by zcsahok** [comment]
@sp7q Is there anything open regarding Hamlib keying?

**Comment by df7cb** [comment]
A new release featuring it... :)

**Comment by dl1jbe** [comment]
When will be the next mayor Debian release?

**Comment by N0NB** [comment]
* On 2024 28 Mar 10:38 -0500, Thomas Beierlein wrote:
> When will be the next mayor Debian release?

Probably sometime around mid 2025 as Debian 12 was released last summer.

73, Nate

-- 
"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."
Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by dl1jbe** [comment]
ok, a new release is overdue anyway.

**Comment by dl1jbe** [comment]
As only a new version release is left off Lets close the issue itself.
