### ISSUE TITLE
Submitting contact with several multipliers

### ISSUE THREAD

**Issue by VictorDenisov** [Tlf/tlf#411]
California QSO party has this concept of county lines. Contact with county line stations gives two multipliers.
Are there any ways for recording several multipliers in one QSO?

**Comment by zcsahok** [comment]
If it were contest exchange + DXCC, then it would be possible with some minor coding. (see last comment for #252 )
Recording two arbitrary multipliers is currently not possible, but it's on the roadmap (that why generic multiplier is called `mult1`...). It'll however require a substantial rework of addmult.

**Comment by zcsahok** [comment]
I have a possible solution in https://github.com/zcsahok/tlf/tree/poc_xmult

The idea is to treat the plugin-generated multiplier string as a list of space separated individual mults and check each of them. The ones that could been applied will be added to the mult field of the log line. There are only 8 chars available, so for two 4-char wide counties the second one gets a bit truncated.

Another basic change is to update `mult1_value` with the actually applied mults, thus moving away from using globals like  `new_mult`.

The rules are just checked in directly under test/rules/cqp_dx. After review they have to be moved to rules/. A separate test for CA stations could also be added.

**Comment by zcsahok** [comment]
![image](https://github.com/Tlf/tlf/assets/15141948/24609625-9dcf-47ee-871a-972993ebece4)

**Comment by zcsahok** [comment]
Yes, it's only truncated in the "applied multipliers" field. The last QSO works TULA again and it is not counted, only KERN. Same for the second QSO on the screenshot.

**Comment by VictorDenisov** [comment]
Are there plans to merge this change?

**Comment by zcsahok** [comment]
I'm working on it.
