### ISSUE TITLE
panel.h not found on some distributions.

### ISSUE THREAD

**Issue by N0NB** [Tlf/tlf#51]
Per this thread:

http://lists.nongnu.org/archive/html/tlf-devel/2015-12/msg00009.html

David reported an issue with his distribution not havng panel.h in /usr/include.  At this time configure.ac does not have an explicit test for the location of panel.h.  Suspect this can be resolved by use of extra macros available from the Autoconf macro archive:

http://www.gnu.org/software/autoconf-archive/

Tom, you may assign me to this, if you can.

**Comment by dl1jbe** [comment]
Seems I can only assign organisation members. Lets see what can be done here.

**Comment by dl1jbe** [comment]
So, now I could assign you.

**Comment by N0NB** [comment]
I have submitted pull request #62 for this issue.

**Comment by dl1jbe** [comment]
Closing the issue as pull request #56 solved the problem. Thanks Nate.
