### ISSUE TITLE
Ubuntu 14

### ISSUE THREAD

**Issue by timseed** [Tlf/tlf#64]
Ubuntu 14 seems to dislike the configure.ac 

I am getting lots of MACRO may not be found ....

Command I am giving is

    autoconf

**Comment by airween** [comment]
Hi Tim,

what's the error message exactly?
Btw, you have to type these:

```
autoreconf --install
./configure --enable-hamlib --enable-fldigi-xmlrpc
make
sudo make install
```

(Note, that the --enable-hamlib and --enable-fldigi-xmlrpc are optional.)

Is this helped?

73, Ervin

**Comment by timseed** [comment]
Hi there,
    I just pulled a fresh copy from github -untar-ed and then followed
your instructions


autoreconf --install
configure.ac:57: warning: macro 'AM_PATH_GLIB_2_0' not found in library
configure.ac:60: error: possibly undefined macro: AM_PATH_GLIB_2_0
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1



It does create configure - but if I try and use it then I get....


./configure
configure: error: cannot find install-sh, install.sh, or shtool in "."
"./.." "./../.."


OS Ubuntu 14 64 Bit. specifically (from uname -a)

Linux photo-lt 3.19.0-42-generic #48~14.04.1-Ubuntu SMP Fri Dec 18
10:24:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


Regards

   Tim



On Fri, January 22, 2016 4:38 am, Ervin Hegedus wrote:
> Hi Tim,
>
>
> what's the error message exactly? Btw, you have to type these:
>
>
> ```
> autoreconf --install ./configure --enable-hamlib --enable-fldigi-xmlrpc
> make sudo make install ```
>
>
> (Note, that the --enable-hamlib and --enable-fldigi-xmlrpc are optional.)
>
>
> Is this helped?
>
>
> 73, Ervin
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tlf/tlf/issues/64#issuecomment-173874206


-- 
Confidentiality Notice: This message, including any attachments, is for
the sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use,disclosure, or
distribution is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply e-mail and destroy all
copies of the original message.

**Comment by timseed** [comment]
A solution seems to be to disable warnings....

    autoreconf --install  --warnings=none

Generates the output files... I am just installing the missing library's and then I can confirm if it is working or not.

**Comment by timseed** [comment]
All working now.... a few missing library's - and the warnings=none was the issue.

It is running on Ubuntu 14.01 64 Bit
